#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AhnNote.Resource", IsApplication=true)]

namespace AhnNote
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int chkChoose = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int editContent = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int editTitle = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int listView = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int txtDate = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int txtTitle = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layoutEditDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layoutListViewItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int NoSDcard = 2130968577;
			
			// aapt resource value: 0x7f04000c
			public const int confirm_batchremove = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int confirm_remove = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int hint_content = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int hint_title = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int menu_add = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int menu_refresh = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int menu_remove = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int prompt = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int remove = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int title_menu_add = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int title_menu_remove = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int view = 2130968589;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
