#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AhnAndroidApp_Second.Resource", IsApplication=true)]

namespace AhnAndroidApp_Second
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int LoveTab1 = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int LoveTab2 = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int MyButton = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int MySpinner = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int MySpinner1 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int MySpinner2 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int MySpinner3 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int MySpinner4 = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int btnChoose = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int chkBox = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int imgPerson = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int listView = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int listView1 = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int txtAge = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int txtGender = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int txtName = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LayoutPerson = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LayoutPerson2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListViewLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListViewLayout2 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListViewLayout3 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TabLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int feedback = 2130968589;
			
			// aapt resource value: 0x7f040002
			public const int love = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int love1 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int love2 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int love3 = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int love4 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int love5 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int love6 = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int loveAhn = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int loveFeng = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int punish1 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int punish2 = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
